package reporter

import (
	"bytes"
	"fmt"
	"io"
	"strings"

	"github.com/pkg/errors"
	"github.com/target/pull-request-code-coverage/internal/plugin/domain"
	"github.com/target/pull-request-code-coverage/internal/plugin/pluginhttp"
	"github.com/target/pull-request-code-coverage/internal/plugin/pluginjson"
)

type GithubPullRequest struct {
	apiKey     string
	apiBaseURL string
	pr         string
	owner      string
	repo       string
	httpClient pluginhttp.Client
	jsonClient pluginjson.Client
}

const (
	HTTPResponseCreated = 201
)

func NewGithubPullRequest(apiKey string, apiBaseURL string, pr string, owner string, repo string, httpClient pluginhttp.Client, jsonClient pluginjson.Client) *GithubPullRequest {
	return &GithubPullRequest{
		apiKey:     apiKey,
		apiBaseURL: apiBaseURL,
		pr:         pr,
		owner:      owner,
		repo:       repo,
		httpClient: httpClient,
		jsonClient: jsonClient,
	}
}

func (s *GithubPullRequest) Write(changedLinesWithCoverage domain.SourceLineCoverageReport) error {

	if changedLinesWithCoverage.TotalLinesWithData() == 0 {
		return nil
	}

	body, bodyErr := s.createCommentBody(changedLinesWithCoverage)

	if bodyErr != nil {
		return errors.Wrap(bodyErr, "Failed creating payload for github")
	}

	url := fmt.Sprintf("%v/repos/%v/%v/issues/%v/comments", strings.TrimRight(s.apiBaseURL, "/"), s.owner, s.repo, s.pr)

	req, newErr := s.httpClient.NewRequest(
		"POST",
		url,
		body)

	if newErr != nil {
		return errors.Wrap(newErr, "Failed creating request to github")
	}

	req.Header.Add("Authorization", "token "+s.apiKey)
	req.Header.Add("Content-Type", "application/json")

	resp, doErr := s.httpClient.Do(req)

	if doErr != nil {
		return errors.Wrap(doErr, "Failed calling github")
	}

	defer func() {
		_ = resp.Body.Close()
	}()

	if resp.StatusCode != HTTPResponseCreated {
		return errors.Errorf("Failed calling github: bad status code: %v", resp.StatusCode)
	}

	return nil
}

func (s *GithubPullRequest) GetName() string {
	return "github pull request  reporter"
}

func (s *GithubPullRequest) createCommentBody(changedLinesWithCoverage domain.SourceLineCoverageReport) (io.Reader, error) {

	modules := collectModules(changedLinesWithCoverage)

	bodyLines := []string{
		"## 📊 Code Coverage — Changed Lines\n",
		"\n",
		"> Coverage is measured **only for the lines this PR changes**, not the whole file or repo.\n",
		"\n",
	}

	if len(modules) > 0 {
		bodyLines = append(bodyLines, fmt.Sprintf("*Modules: %v*\n\n", strings.Join(modules, ", ")))
	}

	bodyLines = append(bodyLines, generateSummaryLines(changedLinesWithCoverage, func(linesWithDataCount int, linesWithoutDataCount int, covered int, missed int) []string {
		totalLines := linesWithDataCount + linesWithoutDataCount
		totalInstructions := covered + missed

		coveredPct := toPercent(safeDiv(float32(covered), float32(totalInstructions), 1))
		missedPct := toPercent(safeDiv(float32(missed), float32(totalInstructions), 0))
		withDataPct := toPercent(safeDiv(float32(linesWithDataCount), float32(totalLines), 1))
		withoutDataPct := toPercent(safeDiv(float32(linesWithoutDataCount), float32(totalLines), 0))

		return []string{
			fmt.Sprintf("### %v Covered Instructions: %.f%% (%d)\n", coverageStatusEmoji(coveredPct), coveredPct, covered),
			"\n",
			"| Metric | Result | What it means |\n",
			"| :-- | :-: | :-- |\n",
			fmt.Sprintf("| 🟢 **Covered Instructions** | **%.f%%** (%d) | Changed code your tests executed. Higher is better. |\n", coveredPct, covered),
			fmt.Sprintf("| 🔴 **Missed Instructions** | %.f%% (%d) | Changed code your tests never ran. Lower is better. |\n", missedPct, missed),
			fmt.Sprintf("| 📈 Lines With Coverage Data | %.f%% (%d) | Changed lines the coverage tool could track. |\n", withDataPct, linesWithDataCount),
			fmt.Sprintf("| ⚪ Lines Without Coverage Data | %.f%% (%d) | Changed lines with no data: comments, blanks, declarations. |\n", withoutDataPct, linesWithoutDataCount),
		}
	})...)

	body := strings.Join(bodyLines, "")
	body += missedInstructionsSection(changedLinesWithCoverage)
	body += "\n<sub>🤖 Generated by <a href=\"https://github.com/target/pull-request-code-coverage\">pull-request-code-coverage</a> — coverage for changed lines only.</sub>\n"

	data := map[string]string{
		"body": body,
	}

	dataBytes, marshalErr := s.jsonClient.Marshal(data)

	if marshalErr != nil {
		return nil, errors.Wrap(marshalErr, "Failed marshalling payload to json")
	}

	return bytes.NewBuffer(dataBytes), nil
}

// missedInstructionsSection renders a collapsible block listing each changed
// line that was not executed by tests. Returns "" when nothing was missed.
func missedInstructionsSection(changedLinesWithCoverage domain.SourceLineCoverageReport) string {
	var missedInstructions string
	missedLineCount := 0

	for _, r := range changedLinesWithCoverage {
		if r.MissedInstructionCount > 0 {
			missedLineCount++
			missedInstructions += fmt.Sprintf("--- %v\n", lineDescription(r.SourceLine))
			missedInstructions += fmt.Sprintf("%v\n", r.LineValue)
		}
	}

	if missedInstructions == "" {
		return ""
	}

	return fmt.Sprintf("\n<details><summary>🔍 Missed instructions (%d)</summary>\n\n", missedLineCount) +
		"```\n" + missedInstructions + "```" + "\n</details>\n"
}

// coverageStatusEmoji maps a covered-instruction percentage to a traffic-light
// status icon, so the headline reads at a glance.
func coverageStatusEmoji(coveredPct float32) string {
	switch {
	case coveredPct >= 80:
		return "🟢"
	case coveredPct >= 50:
		return "🟡"
	default:
		return "🔴"
	}
}

func collectModules(changedLinesWithCoverage domain.SourceLineCoverageReport) []string {
	collector := map[string]bool{}

	for _, line := range changedLinesWithCoverage {
		if line.Module != "" {
			collector[line.Module] = true
		}
	}

	keys := make([]string, 0, len(collector))
	for k := range collector {
		keys = append(keys, k)
	}

	return keys
}
