version: "1"

build: &build
  image: hub.docker.target.com/golang:1.17
  environment:
    - CGO_ENABLED=0
    - GOOS=linux
    - GO111MODULE=on
  commands:
    - go get github.com/axw/gocov/gocov
    - go get github.com/AlekSi/gocov-xml
    - go test -v -coverpkg=./... -coverprofile=coverage.txt ./...
    - go tool cover -func=coverage.txt
    - gocov convert coverage.txt | gocov-xml > ./coverage.xml
    - cat ./coverage.xml
    - go build -a -installsuffix cgo -o bin/plugin

check-pr-code-coverage: &check-pr-code-coverage
  image: hub.docker.target.com/alpine:latest
  environment:
    - PARAMETER_COVERAGE_FILE=./coverage.xml
    - PARAMETER_COVERAGE_TYPE=cobertura
    - PARAMETER_SOURCE_DIRS=/vela/src/git.target.com/TargetOSS/pull-request-code-coverage
    - PARAMETER_RUN_DIR=bin
    - PARAMETER_GH_API_BASE_URL=https://git.target.com
    - PARAMETER_DEBUG=true
  secrets:
    - source: github_pr_token
      target: plugin_gh_api_key
  commands:
    - apk --no-cache add ca-certificates git bash openssh-client
    - ./scripts/start.sh
steps:
  - name: build-push
    image: hub.docker.target.com/golang:1.17
    <<: *build
    ruleset:
      branch:
        - master
      event:
        - push

  - name : check-format-on-pr
    image: hub.docker.target.com/golang:1.17
    commands:
      - make format
    ruleset:
      event:
        - pull_request

  - name : check-lint-on-pr
    image: hub.docker.target.com/golang:1.17
    pull: true
    commands:
      - make lint
    ruleset:
      event:
        - pull_request

  - name : build-on-pr
    <<: *build
    ruleset:
      event:
        - pull_request

  - name: check-pr-code-coverage
    <<: *check-pr-code-coverage
    ruleset:
      event:
        - pull_request

  - name: docker-pull-request
    image: docker.target.com/vela-plugins/kaniko:v0.5.0-1
    ruleset:
      event:
        - pull_request
    secrets: [ docker_password ]
    parameters:
      dry_run: true
      registry: docker.target.com
      repo: docker.target.com/app/pull-request-code-coverage
      tags:
        - latest
        - 1-${BUILD_COMMIT:0:7}
      dockerfile: Dockerfile
      username: svcpejkn001


  - name: docker-push
    image: docker.target.com/vela-plugins/kaniko:v0.5.0-1
    ruleset:
      branch:
        - master
      event:
        - push
    secrets: [ docker_password ]
    parameters:
      registry: docker.target.com
      repo: docker.target.com/app/pull-request-code-coverage
      tags:
        - latest
        - 1-${BUILD_COMMIT:0:7}
      dockerfile: Dockerfile
      username: svcpejkn001

secrets:
  - name: docker_password
    key: tap/vela-secrets/ARTIFACTORY_SVCPEJKN001_BINREPO
    engine: native
    type: shared
  - name: github_pr_token
    engine: native
    type: repo

